steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
      - '.'
      
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy'
    args:
      - 'run'
      - 'deploy'
      - '$REPO_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
      - '--platform'
      - 'gke'
      - '--cluster'
      - '$_CLUSTER_NAME'
      - '--cluster-location'
      - '$_CLUSTER_ZONE'
      - "--port"
      - "5000"